-- Jalankan skrip ini di Supabase SQL Editor sebagai pemilik project.
-- Skrip membuat ulang skema public beserta data awal aplikasi MAGIQ.
DROP TABLE IF EXISTS hasil_ranking;
DROP TABLE IF EXISTS penilaian;
DROP TABLE IF EXISTS kriteria;
DROP TABLE IF EXISTS barista;
DROP TABLE IF EXISTS pengguna;

CREATE TABLE pengguna (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password_hash CHAR(64) NOT NULL,
  nama_lengkap VARCHAR(100) NOT NULL,
  role VARCHAR(30) NOT NULL DEFAULT 'ADMIN',
  dibuat_pada TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE barista (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kode_barista VARCHAR(30) NOT NULL UNIQUE,
  nama VARCHAR(100) NOT NULL,
  dibuat_pada TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  diubah_pada TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE kriteria (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kode VARCHAR(10) NOT NULL UNIQUE,
  nama VARCHAR(100) NOT NULL,
  bobot DECIMAL(10,4) NOT NULL,
  urutan_prioritas INTEGER NOT NULL,
  keterangan VARCHAR(255),
  dibuat_pada TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  diubah_pada TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_kriteria_urutan_prioritas UNIQUE (urutan_prioritas)
);

CREATE TABLE penilaian (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_barista INTEGER NOT NULL,
  id_kriteria INTEGER NOT NULL,
  nilai DECIMAL(10,4) NOT NULL DEFAULT 0,
  dibuat_pada TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  diubah_pada TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_penilaian_barista FOREIGN KEY (id_barista) REFERENCES barista(id) ON DELETE CASCADE,
  CONSTRAINT fk_penilaian_kriteria FOREIGN KEY (id_kriteria) REFERENCES kriteria(id) ON DELETE CASCADE,
  CONSTRAINT uq_barista_kriteria UNIQUE (id_barista, id_kriteria)
);

CREATE TABLE hasil_ranking (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_barista INTEGER NOT NULL,
  nilai_magiq DECIMAL(12,6) NOT NULL,
  peringkat INTEGER NOT NULL,
  dihitung_pada TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_hasil_ranking_barista FOREIGN KEY (id_barista) REFERENCES barista(id) ON DELETE CASCADE
);

CREATE OR REPLACE FUNCTION set_diubah_pada()
RETURNS TRIGGER AS $$
BEGIN
  NEW.diubah_pada = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_barista_diubah_pada
BEFORE UPDATE ON barista
FOR EACH ROW EXECUTE FUNCTION set_diubah_pada();

CREATE TRIGGER trg_kriteria_diubah_pada
BEFORE UPDATE ON kriteria
FOR EACH ROW EXECUTE FUNCTION set_diubah_pada();

CREATE TRIGGER trg_penilaian_diubah_pada
BEFORE UPDATE ON penilaian
FOR EACH ROW EXECUTE FUNCTION set_diubah_pada();

INSERT INTO pengguna (username, password_hash, nama_lengkap, role) VALUES
('admin', 'e1e0797e52d34c7d8d7a3ab2db952aa2775d7df89eac54a655c294d2b6d56909', 'Administrator', 'ADMIN');

INSERT INTO barista (kode_barista, nama)
SELECT 'B' || LPAD((i + 1)::TEXT, 3, '0'),
       'Barista ' || REPEAT(CHR(65 + (i % 26)), (i / 26) + 1)
FROM generate_series(0, 99) AS data(i);

INSERT INTO kriteria (kode, nama, bobot, urutan_prioritas, keterangan) VALUES
('C1', 'Rasa Kopi', 0.4083, 1, 'Tingkat keseimbangan rasa pahit, manis, dan keasaman.'),
('C2', 'Aroma', 0.2417, 2, 'Keharuman kopi yang dihasilkan.'),
('C3', 'Konsistensi Racikan', 0.1583, 3, 'Konsistensi rasa antara satu penyajian dengan lainnya.'),
('C4', 'Penyajian', 0.1028, 4, 'Tampilan dan kerapihan penyajian kopi.'),
('C5', 'Kecepatan Penyajian', 0.0611, 5, 'Kecepatan barista dalam menyajikan kopi.'),
('C6', 'Stabilitas Suhu Penyajian', 0.0278, 6, 'Kestabilan suhu kopi saat disajikan.');

-- Nilai acuan deterministik: C1, C2, C4, C5, C6 berada pada 60--100; C3 ditetapkan 60.
INSERT INTO penilaian (id_barista, id_kriteria, nilai)
SELECT b.id, k.id,
  CASE k.kode
    WHEN 'C1' THEN 60 + 5 * ( i        % 9)
    WHEN 'C2' THEN 60 + 5 * ((i / 9)  % 9)
    WHEN 'C3' THEN 60
    WHEN 'C4' THEN 60 + 5 * ((i * 5 + 2) % 9)
    WHEN 'C5' THEN 60 + 5 * ((i * 7 + 4) % 9)
    WHEN 'C6' THEN 60 + 5 * ((i * 8 + 6) % 9)
  END AS nilai
FROM barista b
CROSS JOIN LATERAL (
  SELECT SUBSTRING(b.kode_barista FROM 2)::INTEGER - 1 AS i
) AS data
CROSS JOIN kriteria k;
