-- Jalankan skrip ini di Supabase SQL Editor sebagai pemilik project.
-- Skrip membuat ulang skema public beserta data awal aplikasi MAGIQ.
DROP TABLE IF EXISTS hasil_ranking;
DROP TABLE IF EXISTS penilaian;
DROP TABLE IF EXISTS kriteria;
DROP TABLE IF EXISTS barista;
DROP TABLE IF EXISTS pengguna;

CREATE TABLE pengguna (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password_hash CHAR(64) NOT NULL,
  nama_lengkap VARCHAR(100) NOT NULL,
  role VARCHAR(30) NOT NULL DEFAULT 'ADMIN',
  dibuat_pada TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE barista (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kode_barista VARCHAR(30) NOT NULL UNIQUE,
  nama VARCHAR(100) NOT NULL,
  divisi VARCHAR(100),
  jabatan VARCHAR(100),
  tanggal_masuk DATE NULL,
  status VARCHAR(10) NOT NULL DEFAULT 'AKTIF' CHECK (status IN ('AKTIF', 'NONAKTIF')),
  dibuat_pada TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  diubah_pada TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE kriteria (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kode VARCHAR(10) NOT NULL UNIQUE,
  nama VARCHAR(100) NOT NULL,
  bobot DECIMAL(10,4) NOT NULL,
  tipe VARCHAR(10) NOT NULL DEFAULT 'BENEFIT' CHECK (tipe IN ('BENEFIT', 'COST')),
  keterangan VARCHAR(255),
  dibuat_pada TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  diubah_pada TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE penilaian (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_barista INTEGER NOT NULL,
  id_kriteria INTEGER NOT NULL,
  nilai DECIMAL(10,4) NOT NULL DEFAULT 0,
  dibuat_pada TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  diubah_pada TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_penilaian_barista FOREIGN KEY (id_barista) REFERENCES barista(id) ON DELETE CASCADE,
  CONSTRAINT fk_penilaian_kriteria FOREIGN KEY (id_kriteria) REFERENCES kriteria(id) ON DELETE CASCADE,
  CONSTRAINT uq_barista_kriteria UNIQUE (id_barista, id_kriteria)
);

CREATE TABLE hasil_ranking (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_barista INTEGER NOT NULL,
  nilai_magiq DECIMAL(12,6) NOT NULL,
  peringkat INTEGER NOT NULL,
  dihitung_pada TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_hasil_ranking_barista FOREIGN KEY (id_barista) REFERENCES barista(id) ON DELETE CASCADE
);

CREATE OR REPLACE FUNCTION set_diubah_pada()
RETURNS TRIGGER AS $$
BEGIN
  NEW.diubah_pada = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_barista_diubah_pada
BEFORE UPDATE ON barista
FOR EACH ROW EXECUTE FUNCTION set_diubah_pada();

CREATE TRIGGER trg_kriteria_diubah_pada
BEFORE UPDATE ON kriteria
FOR EACH ROW EXECUTE FUNCTION set_diubah_pada();

CREATE TRIGGER trg_penilaian_diubah_pada
BEFORE UPDATE ON penilaian
FOR EACH ROW EXECUTE FUNCTION set_diubah_pada();

INSERT INTO pengguna (username, password_hash, nama_lengkap, role) VALUES
('admin', 'e1e0797e52d34c7d8d7a3ab2db952aa2775d7df89eac54a655c294d2b6d56909', 'Administrator', 'ADMIN');

INSERT INTO barista (kode_barista, nama, divisi, jabatan, tanggal_masuk, status) VALUES
('B001', 'Ahmad Fadli', 'Bar', 'Barista', '2021-01-10', 'AKTIF'),
('B002', 'Aldi Pratamas', 'Bar', 'Barista', '2021-01-18', 'AKTIF'),
('B003', 'Andi Saputra', 'Quality Control', 'Senior Barista', '2021-02-03', 'AKTIF'),
('B004', 'Arif Hidayat', 'Service', 'Barista', '2021-02-11', 'AKTIF'),
('B005', 'Bagus Kurniawan', 'Training', 'Asisten Barista', '2021-02-20', 'AKTIF');

INSERT INTO kriteria (kode, nama, bobot, tipe, keterangan) VALUES
('C1', 'Rasa Kopi', 0.4083, 'BENEFIT', 'Tingkat keseimbangan rasa pahit, manis, dan keasaman.'),
('C2', 'Aroma', 0.2417, 'BENEFIT', 'Keharuman kopi yang dihasilkan.'),
('C3', 'Penyajian', 0.1583, 'BENEFIT', 'Tampilan dan kerapihan penyajian kopi.'),
('C4', 'Konsistensi Racikan', 0.1028, 'BENEFIT', 'Konsistensi rasa antara satu penyajian dengan lainnya.'),
('C5', 'Kecepatan Penyajian', 0.0611, 'COST', 'Waktu yang dibutuhkan barista dalam menyajikan kopi; semakin singkat semakin baik.'),
('C6', 'Stabilitas Suhu Penyajian', 0.0278, 'COST', 'Tingkat kestabilan suhu kopi saat disajikan yang diukur menggunakan alat termometer; semakin kecil penyimpangan suhu semakin baik.');

-- Nilai penilaian eksplisit untuk enam kriteria.
INSERT INTO penilaian (id_barista, id_kriteria, nilai)
SELECT b.id, k.id,
  CASE b.kode_barista
    WHEN 'B001' THEN CASE k.kode
      WHEN 'C1' THEN 88 WHEN 'C2' THEN 73 WHEN 'C3' THEN 84
      WHEN 'C4' THEN 95 WHEN 'C5' THEN 10 WHEN 'C6' THEN 3 END
    WHEN 'B002' THEN CASE k.kode
      WHEN 'C1' THEN 95 WHEN 'C2' THEN 80 WHEN 'C3' THEN 91
      WHEN 'C4' THEN 76 WHEN 'C5' THEN 4 WHEN 'C6' THEN 2 END
    WHEN 'B003' THEN CASE k.kode
      WHEN 'C1' THEN 76 WHEN 'C2' THEN 87 WHEN 'C3' THEN 72
      WHEN 'C4' THEN 83 WHEN 'C5' THEN 6 WHEN 'C6' THEN 4 END
    WHEN 'B004' THEN CASE k.kode
      WHEN 'C1' THEN 83 WHEN 'C2' THEN 94 WHEN 'C3' THEN 79
      WHEN 'C4' THEN 90 WHEN 'C5' THEN 8 WHEN 'C6' THEN 3 END
    WHEN 'B005' THEN CASE k.kode
      WHEN 'C1' THEN 90 WHEN 'C2' THEN 75 WHEN 'C3' THEN 86
      WHEN 'C4' THEN 71 WHEN 'C5' THEN 10 WHEN 'C6' THEN 5 END
  END AS nilai
FROM barista b
CROSS JOIN kriteria k;
